---
title: "Um Dashboard"
author: "Elton Dantas e Rebeca Beltrão"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(plotly)


respostas = read_csv(here::here("data/enade-ccc-2017.csv"),
                     col_types = "cccdccdddc")

```

### Chart 1

```{r fig.height=12, fig.width=6}
# Oportunidades de intercâmbio

dados = respostas %>%
    na.omit() %>%
    group_by(IES,tema) %>%
    filter(tema == "Oport. Intercâmbio no país" | tema == "Oport. Intercâmbio exterior") %>%
    summarise(media_ies = mean(media), ) %>%
    glimpse()


dados %>% 
    plot_ly(x = ~media_ies,
            y = ~reorder(IES,media_ies),
            type = "scatter", 
            color = ~tema,
            colors = "Paired",
            text = ~paste('IES: ', IES,
                          '<br>Media: ', media_ies)) %>% 
    layout(title = "Oportunidades de intercambio no pais ou exterior nas IES brasileiras",
           yaxis = list(title = "Universidade"),
           xaxis = list(title = "Media"))

<<<<<<< HEAD
=======
    
>>>>>>> 5c4f4dd99c765e5e6a08c30b756958716586c784
```

### Chart 2

```{r}
# Perfil técnico
t = respostas %>%
    na.omit(.) %>%
    group_by(IES,
             tema) %>%
    filter(tema == "Ambiente p/ aulas práticas" |
            tema == "Atividades práticas suficientes" |
            tema == "Conteúdo útil p/ prática" |
            tema == "Oport. de extensão" |
            tema == "Equipamentos suficientes") %>%
    summarise(media_t = mean(media)) %>% 
    ggplot(aes(x = media_t,
               y = reorder(IES,media_t),
               color = tema)) +
    geom_point(alpha = .5) +
    geom_point(data = respostas %>%
                    na.omit(.) %>%
                    group_by(IES) %>%
                    filter(tema == "Ambiente p/ aulas práticas" |
                            tema == "Atividades práticas suficientes" |
                            tema == "Conteúdo útil p/ prática" |
                            tema == "Oport. de extensão" |
                            tema == "Equipamentos suficientes") %>% 
                    summarise(media_t = mean(media)), 
                               color = "gray22")+
    labs(x = "Media")
ggplotly(t)

    
```

### Chart 3

```{r}
# Perfil científico
c= respostas %>%
    na.omit(.) %>%
    group_by(IES,
             tema) %>%
    filter(tema == "Comunicação oral e escrita" |
            tema == "Iniciação científica" |
            tema == "Monitores" |
            tema == "Reflexão e argumentação" |
            tema == "Pensamento crítico") %>%
    summarise(media_c = mean(media)) %>% 
    ggplot(aes(x = media_c,
               y = reorder(IES,media_c),
               color = tema)) +
    geom_point(alpha = .5) +
    geom_point(data = respostas %>%
                    na.omit(.) %>%
                    group_by(IES) %>%
                    filter(tema == "Comunicação oral e escrita" |
                            tema == "Iniciação científica" |
                            tema == "Monitores" |
                            tema == "Reflexão e argumentação" |
                            tema == "Pensamento crítico") %>% 
                    summarise(media_c = mean(media)), 
                               color = "black")+
    labs(x = "Media")
ggplotly(c)

```

```{r}
# Comparação dos perfis

cientifico = respostas %>%
                na.omit(.) %>%
                group_by(IES,
                         media) %>%
                filter(
                    tema == "Comunicação oral e escrita" |
                    tema == "Iniciação científica" |
                    tema == "Monitores" |
                    tema == "Reflexão e argumentação" |
                    tema == "Pensamento crítico") %>%
                summarise(media_c = mean(media)) %>%
                select(IES,media_c) %>%
                summarise(media_c = mean(media_c))
                
tecnico =  respostas %>%
                na.omit(.) %>%
                group_by(IES,
                         media) %>%
                filter(
                        tema == "Ambiente p/ aulas práticas" |
                        tema == "Atividades práticas suficientes" |
                        tema == "Conteúdo útil p/ prática" |
                        tema == "Oport. de extensão" |
                        tema == "Equipamentos suficientes") %>%
                summarise(media_t = mean(media)) %>%
                # mutate(media_t = mean(media)) %>% 
                select(IES,media_t) %>% 
                # group_by(IES) %>% 
                summarise(media_t = mean(media_t))

perfis = add_column(cientifico, media_t = tecnico$media_t)

p = perfis %>%
    mutate(diferenca = media_c - media_t) %>% 
    ggplot(aes(x = reorder(IES,diferenca), y = diferenca, fill = diferenca > 0)) +
    geom_col() +
    labs(
        x = "",
        y = "Diferença = nível científico - nível técnico",
        title = "Perfis das IES com curso de Ciência da Computação",
        subtitle = "",
        caption = ""
    ) +
    coord_flip()
ggplotly(p)
```