---
title: "Um Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(hrbrthemes)
library(plotly)

theme_set(theme_ipsum())

respostas = read_csv(here::here("data/enade-ccc-2017.csv"),
                     col_types = "cccdccdddc")

cursos = respostas %>% 
    group_by(UF) %>% 
    summarise(n = n(), 
              media = mean(media))

criterios = respostas %>% 
    group_by(UF, categoria) %>% 
    summarise(media = mean(media))

```

Column {data-width=650}
-----------------------------------------------------------------------

### Parte 1

```{r}
criterios %>%
    filter(categoria != "Outros") %>%
    ggplot(aes(
        x = reorder(UF, media),
        y = reorder(categoria, media),
        fill = media
    )) +
    geom_tile() + 
    scale_fill_viridis() + 
    theme(legend.position = "bottom")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Parte 2

```{r}
cursos %>% 
    ggplot(aes(x = UF, y = media)) + 
    geom_col() + 
    coord_flip()
```

### Parte 3

```{r}
cursos %>% 
    ggplot(aes(x = UF, y = n)) + 
    geom_col()
```

```{r fig.height=12, fig.width=6}
# Oportunidades de intercâmbio

dados = respostas %>%
    na.omit() %>%
    group_by(IES,tema) %>%
    filter(tema == "Oport. Intercâmbio no país" | tema == "Oport. Intercâmbio exterior") %>%
    summarise(media_ies = mean(media)) %>%
    glimpse()


dados %>% 
    plot_ly(y = ~IES,
            x = ~media_ies, 
            type = "scatter", 
            color = ~tema,
            text = ~paste('IES: ', IES,
                          '<br>Media: ', media_ies)) %>% 
    layout(title = "Oportunidades de intercambio no pais ou exterior nas IES brasileiras",
           yaxis = list(title = "Universidade"),
           xaxis = list(title = "Media"))
```

```{r}
# Perfil técnico
t = respostas %>%
    na.omit(.) %>%
    group_by(UF,
             IES,
             tema) %>%
    filter(tema == "Ambiente p/ aulas práticas" |
            tema == "Atividades práticas suficientes" |
            tema == "Conteúdo útil p/ prática" |
            tema == "Oport. de extensão" |
            tema == "Equipamentos suficientes") %>%
    summarise(media_t = mean(media)) %>% 
    ggplot(aes(x = media_t,
               y = IES,
               color = tema)) +
    geom_point()
ggplotly(t)
    
# Perfil científico
c = respostas %>%
    na.omit(.) %>%
    group_by(UF,
             IES,
             tema) %>%
    filter(tema == "Comunicação oral e escrita" |
            tema == "Iniciação científica" |
            tema == "Monitores" |
            tema == "Reflexão e argumentação" |
            tema == "Pensamento crítico") %>%
    summarise(media_c = mean(media)) %>% 
    ggplot(aes(x = media_c,
               y = IES,
               color = tema)) +
    geom_point()
ggplotly(c)   
```


```{r}

```

